version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: loyalty-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lms-network

  redis:
    image: redis:7
    container_name: loyalty-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lms-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - JWT_SECRET=mysupersecurejwtsecretkeyforlms2026project
    ports:
      - "8082:8082"
    networks:
      - lms-network

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - lms-network

  member-service:
    build: ./member-service
    container_name: member-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      customer-service:
        condition: service_started
    ports:
      - "8084:8084"
    networks:
      - lms-network

  partner-service:
    build: ./partner-service
    container_name: partner-service
    depends_on: 
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      member-service:
        condition: service_started
    ports:
      - "8085:8085"
    networks:
      - lms-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - customer-service
      - member-service
      - redis
      - partner-service      
    environment:
      - JWT_SECRET=mysupersecurejwtsecretkeyforlms2026project
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  postgres_data: