server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**

        - id: customer-service
          uri: http://customer-service:8083
          predicates:
            - Path=/customers/**

        - id: member-service
          uri: http://member-service:8084
          predicates:
            - Path=/members/**
            
  security:
    oauth2:
      resourceserver:
        jwt: 
          secret-key: ${JWT_SECRET}